version: '3'

services:
  clearing:
    container_name: clearing
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ENV: dev
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      POSTGRES_DB: clearing-team
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres

  postgres:
    image: 'postgres:13.5-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clearing-team
      - PGDATA=/data/postgres_dev
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres -d clearing-team
      interval: 10s
      timeout: 20s
      retries: 3
