version: '3'

services:
  postgres:
    image: 'postgres:13.5-alpine'
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=clearing
      - PGDATA=/data/postgres
    ports:
      - '5432:5432'
  pubsub:
    image: 'gcr.io/google.com/cloudsdktool/cloud-sdk:emulators'
    entrypoint: 'gcloud beta emulators pubsub start --project=test-e2e --host-port=0.0.0.0:8085'
    ports:
      - '8085:8085'
